name: Build Scan Push Images

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login GHCR (pas besoin de secret, GITHUB_TOKEN suffit)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build backend
      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest backend
          docker tag ghcr.io/${{ github.repository }}/backend:latest ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

      # Scan backend image
      - name: Trivy scan backend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/backend:latest
          severity: HIGH,CRITICAL
          exit-code: "1"

      # Push backend
      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

      # Build frontend
      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest frontend
          docker tag ghcr.io/${{ github.repository }}/frontend:latest ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

      # Scan frontend image
      - name: Trivy scan frontend image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/frontend:latest
          severity: HIGH,CRITICAL
          exit-code: "1"

      # Push frontend
      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
